version: 2.1
orbs:
  terraform: circleci/terraform@3.1
parameters:
  infrastructure:
    type: boolean
    default: false
  image-create:
    type: boolean
    default: false
jobs:
  create-infrastructure:
    executor: terraform/default
    steps:
      - checkout
      - run: >
          cd infrastructure/

          terraform init -backend-config="bucket=$STATE_BUCKET" -backend-config="key=terraform.tfstate" -backend-config="region=$REGION"

          terraform apply -auto-approve

          terraform output -raw rds_url > db_ip.txt

          aws s3 cp ./db_ip.txt s3://${STATE_BUCKET}/
      - persist_to_workspace:
          root: .
          paths:
            - .
  destroy-infrastructure:
    executor: terraform/default
    steps:
      - checkout
      - attach_workspace:
          at: .
      - terraform/destroy:
          path: infrastructure/
  test-cluster:
    docker:
      - image: cimg/aws:2022.11
    steps:
      - run: >
          aws ecs describe-clusters --cluster $TF_VAR_cluster_name > cluster.json

          if grep -q '"status": "ACTIVE"' cluster.json; then exit 0; else exit 1; fi
  build-and-push-image:
    docker:
      - image: cimg/aws:2022.11
    steps:
      - run: >
          cd app/

          aws s3 cp s3://${STATE_BUCKET}/db_ip.txt .

          sed -i "s/<DB_IP>/$(cat db_ip.txt)/g" Dockerfile

          docker build -t django-app .

          aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin ${AWS_ACCOUNT_ID}.dkr.ecr.us-east-1.amazonaws.com/${TF_VAR_ecr_repo}

          docker tag django-app:latest ${AWS_ACCOUNT_ID}.dkr.ecr.us-east-1.amazonaws.com/${TF_VAR_ecr_repo}

          docker push ${AWS_ACCOUNT_ID}.dkr.ecr.us-east-1.amazonaws.com/${TF_VAR_ecr_repo}
  dive-test:
    docker:
      - image: cimg/aws:2022.11
    steps:
      - run: >
          sudo wget
          https://github.com/wagoodman/dive/releases/download/v0.9.2/dive_0.9.2_linux_amd64.deb

          sudo apt install ./dive_0.9.2_linux_amd64.deb

          aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin ${AWS_ACCOUNT_ID}.dkr.ecr.us-east-1.amazonaws.com/${TF_VAR_ecr_repo}

          sudo dive --ci ${AWS_ACCOUNT_ID}.dkr.ecr.us-east-1.amazonaws.com/${TF_VAR_ecr_repo}:latest
  deploy-image:
    docker:
      - image: cimg/aws:2022.11
    steps:
      - run: >
          aws ecs update-service --cluster $TF_VAR_cluster_name --service
          $TF_VAR_service_name --force-new-deployment
workflows:
  infrastructure-deploy:
    when: << pipeline.parameters.infrastructure >>
    jobs:
      - create-infrastructure
      - hold-destroy:
          type: approval
          requires: 
            - create-infrastructure
      - destroy-infrastructure:
          requires: 
            - hold-destroy
  app-deploy:
    when: << pipeline.parameters.image-create >>
    jobs:
      - test-cluster
      - build-and-push-image:
          requires:
            - test-cluster
      - dive-test:
          requires:
            - build-and-push-image
      - deploy-image:
          requires:
            - dive-test
