version: 2.1
orbs:
  terraform: circleci/terraform@3.1
  aws-cli: circleci/aws-cli@3.1
  docker: circleci/docker@2.2.0

parameters:
  infrastructure:
    type: boolean
    default: false
  image-create:
    type: boolean
    default: false
jobs:
  create-infrastructure:
    executor: terraform/default
    steps:
      - checkout
      - run: |
          cd infrastructure/

          terraform init -backend-config="bucket=$STATE_BUCKET" -backend-config="key=terraform.tfstate" -backend-config="region=$REGION"

          terraform apply -auto-approve

      - persist_to_workspace:
          root: .
          paths:
            - .

  destroy-infrastructure:
    executor: terraform/default
    steps:
      - checkout
      - attach_workspace:
          at: .
      - terraform/destroy:
          path: infrastructure/

  test-cluster:
    docker:
      - image: cimg/aws:2022.11
    steps:
      - checkout
      - run: |
          aws ecs describe-clusters --cluster $TF_VAR_cluster_name --region $TF_VAR_region  --query 'clusters[*].[status]' --output text > status.txt
          if [[ $(< status.txt) = "ACTIVE" ]] ; then exit 0; else exit 1; fi

  build-and-push-image:
    machine:
      image: ubuntu-2004:202010-01
    steps:
      - checkout
      - run: |
          aws rds describe-db-instances --region $TF_VAR_region --query 'DBInstances[*].[Endpoint.Address]' --output text > db_ip.txt
      - run: sed -i "s/<DB_IP>/$(cat ./db_ip.txt)/g" app/Dockerfile
      - run: |
          aws ecr get-login-password --region $TF_VAR_region | docker login --username AWS --password-stdin ${AWS_ACCOUNT_ID}.dkr.ecr.us-east-1.amazonaws.com/${TF_VAR_ecr_repo}
          cd app/
          docker build -t django-app .
          docker images
          docker tag django-app:latest ${AWS_ACCOUNT_ID}.dkr.ecr.us-east-1.amazonaws.com/${TF_VAR_ecr_repo}
          docker push ${AWS_ACCOUNT_ID}.dkr.ecr.us-east-1.amazonaws.com/${TF_VAR_ecr_repo}

  dive-test:
    machine:
      image: ubuntu-2004:202010-01
    steps:
      - run: |
          sudo wget https://github.com/wagoodman/dive/releases/download/v0.9.2/dive_0.9.2_linux_amd64.deb
          sudo apt install ./dive_0.9.2_linux_amd64.deb
          aws ecr get-login-password --region $TF_VAR_region | docker login --username AWS --password-stdin ${AWS_ACCOUNT_ID}.dkr.ecr.us-east-1.amazonaws.com/${TF_VAR_ecr_repo}
          docker pull 841962000336.dkr.ecr.us-east-1.amazonaws.com/django-repo:latest
          docker images
          sudo dive --ci 841962000336.dkr.ecr.us-east-1.amazonaws.com/django-repo:latest

  deploy-image:
    docker:
      - image: cimg/aws:2022.11
    steps:
      - run: |
          aws ecs update-service --region $TF_VAR_region --cluster $TF_VAR_cluster_name --service $TF_VAR_service_name --force-new-deployment

workflows:
  infrastructure-deploy:
    when: << pipeline.parameters.infrastructure >>
    jobs:
      - create-infrastructure
      - hold-destroy:
          type: approval
          requires: 
            - create-infrastructure
      - destroy-infrastructure:
          requires: 
            - hold-destroy

  app-deploy:
    when: << pipeline.parameters.image-create >>
    jobs:
      - test-cluster
      - build-and-push-image:
          requires:
            - test-cluster
      - dive-test:
          requires:
            - build-and-push-image
      - hold-deploy: 
          type: approval
          requires:
            - build-and-push-image
      - deploy-image:
          requires:
            - hold-deploy
